import {studentNeedOptions} from './student-needs.js';
export const MONTH='2026-10';
export async function dashboard(db,user){
const school=(await db.query('SELECT id,name FROM schools WHERE id=$1',[user.schoolId])).rows[0];
const groupRows=(await db.query(`SELECT g.*,p.name AS teacher_name,l.id AS lesson_id,l.lesson_date::text AS date FROM groups g JOIN profiles p ON p.id=g.teacher_id JOIN lessons l ON l.group_id=g.id WHERE g.school_id=$1 AND ${user.role==='teacher'?'g.teacher_id=$2':'EXISTS(SELECT 1 FROM memberships m WHERE m.group_id=g.id AND m.student_id=$2)'} ORDER BY l.lesson_date,g.time`,[user.schoolId,user.id])).rows;
const groupIds=groupRows.map(g=>g.id);
const memberRows=(await db.query(`SELECT m.* FROM memberships m WHERE m.group_id=ANY($1::text[]) ${user.role==='student'?'AND m.student_id=$2':''}` ,user.role==='student'?[groupIds,user.id]:[groupIds])).rows;
const studentIds=[...new Set(memberRows.map(m=>m.student_id))];
const students=(await db.query('SELECT s.*,p.name FROM students s JOIN profiles p ON p.id=s.profile_id WHERE s.profile_id=ANY($1::text[]) ORDER BY p.name',[studentIds])).rows;
const sn=(await db.query('SELECT sn.student_id,n.* FROM student_needs sn JOIN needs n ON n.code=sn.need_code WHERE sn.student_id=ANY($1::text[])',[studentIds])).rows;
const horses=(await db.query('SELECT * FROM horses WHERE school_id=$1 ORDER BY name',[user.schoolId])).rows;
const hn=(await db.query('SELECT hn.horse_id,n.* FROM horse_needs hn JOIN needs n ON n.code=hn.need_code JOIN horses h ON h.id=hn.horse_id WHERE h.school_id=$1',[user.schoolId])).rows;
const activities=(await db.query('SELECT ha.* FROM horse_activities ha JOIN horses h ON h.id=ha.horse_id WHERE h.school_id=$1',[user.schoolId])).rows;
const wishRows=(await db.query('SELECT * FROM wishes WHERE group_id=ANY($1::text[]) AND student_id=ANY($2::text[]) AND month=$3',[groupIds,studentIds,MONTH])).rows;
const assignmentRows=(await db.query('SELECT a.*,l.group_id,d.status FROM assignments a JOIN lessons l ON l.id=a.lesson_id JOIN distributions d ON d.group_id=l.group_id WHERE l.group_id=ANY($1::text[]) AND a.student_id=ANY($2::text[])',[groupIds,studentIds])).rows;
const audit=(await db.query(`SELECT a.id::text,p.name AS actor_name,a.action,a.detail,a.created_at FROM audit a JOIN profiles p ON p.id=a.actor_id WHERE a.school_id=$1 ${user.role==='student'?'AND a.actor_id=$2':''} ORDER BY a.id DESC LIMIT 30`,user.role==='student'?[user.schoolId,user.id]:[user.schoolId])).rows;
return {school,user,month:MONTH,studentNeedOptions,horses:horses.map(h=>({id:h.id,name:h.name,imageUrl:h.image_path,imageKind:h.image_kind,kind:h.kind,heightCm:h.height_cm,temperament:h.temperament,description:h.description,status:h.status,availabilityReason:h.availability_reason,maxDailyLessons:h.max_daily_lessons,restDay:h.rest_day,maxWeeklyJumps:h.max_weekly_jumps,minRiderLevel:h.min_rider_level,maxRiderWeightKg:h.max_rider_weight_kg,allowedActivities:activities.filter(a=>a.horse_id===h.id).map(a=>a.activity),needs:hn.filter(n=>n.horse_id===h.id).map(n=>({code:n.code,label:n.label})),source:h.source,syntheticFields:h.synthetic_fields})),students:students.map(s=>({id:s.profile_id,name:s.name,initials:s.name.split(' ').map(n=>n[0]).slice(0,2).join(''),level:s.level,heightCm:s.height_cm,weightKg:s.weight_kg,needs:sn.filter(n=>n.student_id===s.profile_id).map(n=>({code:n.code,label:n.label})),groupIds:memberRows.filter(m=>m.student_id===s.profile_id).map(m=>m.group_id),historyState:s.history_state})),groups:groupRows.map(g=>({id:g.id,name:g.name,level:g.level,dayLabel:g.day_label,time:g.time,activity:g.activity,durationMinutes:g.duration_minutes,studentIds:memberRows.filter(m=>m.group_id===g.id).map(m=>m.student_id),teacherName:g.teacher_name,lessonId:g.lesson_id,date:g.date})),wishes:memberRows.map(m=>({studentId:m.student_id,groupId:m.group_id,month:MONTH,horseIds:wishRows.filter(w=>w.student_id===m.student_id&&w.group_id===m.group_id).map(w=>w.horse_id)})),assignments:assignmentRows.map(a=>({studentId:a.student_id,groupId:a.group_id,lessonId:a.lesson_id,horseId:a.horse_id,reason:a.reason,status:a.status})),history:audit.map(a=>({id:a.id,actorName:a.actor_name,action:a.action,detail:a.detail,createdAt:a.created_at})),teacherName:user.role==='teacher'?user.name:undefined};
}
