import express from 'express';
import crypto from 'node:crypto';
import {existsSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {pool,query,initialize,transaction} from './db.js';
import {seed} from './seed.js';
import {seedHorseImages} from './horse-images.js';
import {studentNeedOptions} from './student-needs.js';
import {importCaseStudents} from './case-students.js';
import {dashboard,MONTH} from './data.js';
import {ApiError,context,validate,propose,priorities,safety} from './matching.js';
const app=express();app.disable('x-powered-by');app.use(express.json({limit:'100kb'}));
app.use((req,res,next)=>{if(['POST','PUT','PATCH','DELETE'].includes(req.method)&&req.headers.origin){const origin=new URL(req.headers.origin);if(origin.host!==req.headers.host&&!['localhost:5173','127.0.0.1:5173'].includes(origin.host))return res.status(403).json({message:'Ukendt afsender.'});}next();});
const cookie=req=>req.headers.cookie?.split(';').map(c=>c.trim()).find(c=>c.startsWith('stald_session='))?.split('=')[1];
const userRow=r=>({id:r.id,name:r.name,role:r.role,schoolId:r.school_id,schoolName:r.school_name});
app.get('/api/health',async(req,res)=>{await query('SELECT 1');res.json({status:'ok',database:'postgresql'});});
app.get('/api/bootstrap',async(req,res)=>{const schools=(await query('SELECT id,name FROM schools ORDER BY name')).rows;const profiles=(await query('SELECT p.*,s.name AS school_name FROM profiles p JOIN schools s ON s.id=p.school_id ORDER BY p.role DESC,p.name')).rows.map(userRow);res.json({schools,profiles});});
app.post('/api/session',async(req,res)=>{const {profileId}=req.body;const row=(await query('SELECT p.*,s.name AS school_name FROM profiles p JOIN schools s ON s.id=p.school_id WHERE p.id=$1',[profileId])).rows[0];if(!row)throw new ApiError(400,'Vælg en gyldig demonstrationsprofil.');const token=crypto.randomBytes(32).toString('hex');await query('INSERT INTO sessions VALUES($1,$2,now()+interval \'7 days\')',[token,profileId]);res.cookie('stald_session',token,{httpOnly:true,sameSite:'lax',secure:process.env.COOKIE_SECURE==='true',maxAge:7*86400000});res.json({user:userRow(row)});});
app.use('/api',async(req,res,next)=>{const token=cookie(req);const row=token?(await query('SELECT p.*,sc.name AS school_name FROM sessions s JOIN profiles p ON p.id=s.profile_id JOIN schools sc ON sc.id=p.school_id WHERE s.token=$1 AND s.expires_at>now()',[token])).rows[0]:null;if(!row)return res.status(401).json({message:'Vælg en profil for at fortsætte.'});req.user=userRow(row);next();});
app.get('/api/session',(req,res)=>res.json({user:req.user}));
app.delete('/api/session',async(req,res)=>{await query('DELETE FROM sessions WHERE token=$1',[cookie(req)]);res.clearCookie('stald_session',{httpOnly:true,sameSite:'lax'});res.json({ok:true});});
app.get('/api/dashboard',async(req,res)=>{const data=await dashboard(pool,req.user);const dists=(await query('SELECT * FROM distributions WHERE group_id=ANY($1::text[])',[data.groups.map(g=>g.id)])).rows;const decisions=(await query('SELECT * FROM decisions WHERE group_id=ANY($1::text[])',[data.groups.map(g=>g.id)])).rows;for(const g of data.groups){const d=dists.find(d=>d.group_id===g.id);g.revision=d?.revision||0;g.status=d?.status||'draft';g.distributionStatus=g.status;g.decisions=decisions.filter(d=>d.group_id===g.id).map(d=>({horseId:d.horse_id,studentId:d.student_id,reason:d.reason}));g.conflicts=req.user.role==='teacher'?priorities(await context(pool,req.user,g.id)):[];}res.json(data);});
async function lockSchool(db,user){await db.query('SELECT id FROM schools WHERE id=$1 FOR UPDATE',[user.schoolId]);}
async function audit(db,user,action,detail){await db.query('INSERT INTO audit(school_id,actor_id,action,detail) VALUES($1,$2,$3,$4)',[user.schoolId,user.id,action,detail]);}
async function state(db,groupId){return {distribution:(await db.query('SELECT * FROM distributions WHERE group_id=$1',[groupId])).rows[0],assignments:(await db.query('SELECT a.* FROM assignments a JOIN lessons l ON l.id=a.lesson_id WHERE l.group_id=$1 ORDER BY a.student_id',[groupId])).rows,decisions:(await db.query('SELECT * FROM decisions WHERE group_id=$1 ORDER BY horse_id',[groupId])).rows};}
async function snapshot(db,user,groupId,action,before){await db.query('INSERT INTO distribution_versions(group_id,actor_id,action,before_state,after_state) VALUES($1,$2,$3,$4,$5)',[groupId,user.id,action,JSON.stringify(before),JSON.stringify(await state(db,groupId))]);}
async function invalidate(db,user){await db.query("UPDATE distributions SET revision=revision+1,status='draft' WHERE group_id IN(SELECT id FROM groups WHERE school_id=$1)",[user.schoolId]);}
app.put('/api/profile/needs',async(req,res)=>{
  if(req.user.role!=='student')throw new ApiError(403,'Kun elever kan ændre deres egne hensyn.');
  const {needCodes}=req.body;
  const allowed=new Set(studentNeedOptions.map(n=>n.code));
  if(Object.keys(req.body).some(k=>k!=='needCodes')||!Array.isArray(needCodes)||needCodes.length>allowed.size||new Set(needCodes).size!==needCodes.length||needCodes.some(code=>typeof code!=='string'||!allowed.has(code)))throw new ApiError(422,'Vælg gyldige hensyn fra listen.');
  await transaction(async db=>{
    await lockSchool(db,req.user);
    const old=(await db.query('SELECT need_code FROM student_needs WHERE student_id=$1 ORDER BY need_code',[req.user.id])).rows.map(n=>n.need_code);
    if(JSON.stringify(old)===JSON.stringify([...needCodes].sort()))return;
    await db.query('DELETE FROM student_needs WHERE student_id=$1',[req.user.id]);
    for(const code of needCodes){const option=studentNeedOptions.find(n=>n.code===code);await db.query('INSERT INTO needs VALUES($1,$2) ON CONFLICT DO NOTHING',[code,option.label]);await db.query('INSERT INTO student_needs VALUES($1,$2)',[req.user.id,code]);}
    await db.query("UPDATE distributions SET revision=revision+1,status='draft' WHERE group_id IN(SELECT group_id FROM memberships WHERE student_id=$1)",[req.user.id]);
    await audit(db,req.user,'Elevhensyn opdateret',needCodes.length?needCodes.map(code=>studentNeedOptions.find(n=>n.code===code).label).join(' · '):'Ingen særlige hensyn registreret.');
  });
  res.json({ok:true});
});
app.put('/api/wishes',async(req,res)=>{if(req.user.role!=='student')throw new ApiError(403,'Kun elever kan gemme deres egne ønsker.');const {groupId,horseIds,month=MONTH}=req.body;if(month!==MONTH||!Array.isArray(horseIds)||horseIds.length>3||new Set(horseIds).size!==horseIds.length||horseIds.some(id=>typeof id!=='string'))throw new ApiError(422,'Vælg op til tre forskellige heste for den aktuelle måned.');await transaction(async db=>{await lockSchool(db,req.user);const allowed=(await db.query('SELECT g.id FROM groups g JOIN memberships m ON m.group_id=g.id WHERE g.id=$1 AND g.school_id=$2 AND m.student_id=$3',[groupId,req.user.schoolId,req.user.id])).rows;if(!allowed.length)throw new ApiError(403,'Du er ikke elev på dette hold.');const horses=(await db.query('SELECT id FROM horses WHERE school_id=$1 AND id=ANY($2::text[])',[req.user.schoolId,horseIds])).rows;if(horses.length!==horseIds.length)throw new ApiError(422,'En valgt hest findes ikke på rideskolen.');await db.query('DELETE FROM wishes WHERE student_id=$1 AND group_id=$2 AND month=$3',[req.user.id,groupId,month]);for(const id of horseIds)await db.query('INSERT INTO wishes VALUES($1,$2,$3,$4)',[req.user.id,groupId,month,id]);await invalidate(db,req.user);await audit(db,req.user,'Ønsker gemt',`${horseIds.length} ligeværdige ønsker for ${month}.`);});res.json({ok:true});});
app.post('/api/distributions/propose',async(req,res)=>{const result=await transaction(async db=>{await lockSchool(db,req.user);const ctx=await context(db,req.user,req.body.groupId);const before=await state(db,ctx.group.id);const result=propose(ctx);await db.query('DELETE FROM assignments WHERE lesson_id=$1',[ctx.group.lessonId]);for(const a of result.assignments)await db.query('INSERT INTO assignments VALUES($1,$2,$3,$4)',[a.lessonId,a.studentId,a.horseId,a.reason]);const revision=ctx.dist.revision+1;await db.query("UPDATE distributions SET revision=$2,status='draft' WHERE group_id=$1",[ctx.group.id,revision]);await snapshot(db,req.user,ctx.group.id,'proposed',before);await audit(db,req.user,'Forslag lavet',`Matchforslag for ${ctx.group.name}.`);return {...result,revision};});res.json(result);});
app.put('/api/distributions/:groupId',async(req,res)=>{const result=await transaction(async db=>{await lockSchool(db,req.user);const ctx=await context(db,req.user,req.params.groupId);if(req.body.revision!==ctx.dist.revision)throw new ApiError(409,'Fordelingen er ændret. Genindlæs før du gemmer.',{revision:ctx.dist.revision});const before=await state(db,ctx.group.id);const assignments=req.body.assignments;if(!Array.isArray(assignments)||assignments.length>ctx.group.studentIds.length)throw new ApiError(422,'Ugyldige tildelinger.');const decisionRows=req.body.decisions||[];if(!Array.isArray(decisionRows))throw new ApiError(422,'Ugyldige lærerbeslutninger.');for(const d of decisionRows){if(!ctx.group.studentIds.includes(d.studentId)||!ctx.data.horses.some(h=>h.id===d.horseId)||typeof d.reason!=='string'||d.reason.trim().length<3)throw new ApiError(422,'Et lærervalg kræver en gyldig elev, hest og begrundelse.');await db.query('INSERT INTO decisions VALUES($1,$2,$3,$4) ON CONFLICT(group_id,horse_id) DO UPDATE SET student_id=EXCLUDED.student_id,reason=EXCLUDED.reason',[ctx.group.id,d.horseId,d.studentId,d.reason.trim()]);}ctx.decisions=(await db.query('SELECT * FROM decisions WHERE group_id=$1',[ctx.group.id])).rows;const conflicts=validate(ctx,assignments);const safetyErrors=conflicts.filter(c=>['safety','duplicate','priority'].includes(c.type));if(safetyErrors.length)throw new ApiError(422,'Tildelingen overholder ikke reglerne.',{conflicts:safetyErrors,revision:ctx.dist.revision});await db.query('DELETE FROM assignments WHERE lesson_id=$1',[ctx.group.lessonId]);for(const a of assignments){const d=ctx.decisions.find(d=>d.horse_id===a.horseId&&d.student_id===a.studentId);await db.query('INSERT INTO assignments VALUES($1,$2,$3,$4)',[ctx.group.lessonId,a.studentId,a.horseId,d?.reason||a.reason||'Lærerens tildeling']);}const revision=ctx.dist.revision+1;await db.query("UPDATE distributions SET revision=$2,status='draft' WHERE group_id=$1",[ctx.group.id,revision]);await snapshot(db,req.user,ctx.group.id,'edited',before);await audit(db,req.user,'Fordeling rettet',`${ctx.group.name}: lærerens ændringer og beslutninger gemt.`);return {ok:true,revision,conflicts};});res.json(result);});
app.post('/api/distributions/:groupId/approve',async(req,res)=>{const result=await transaction(async db=>{await lockSchool(db,req.user);const fingerprint=crypto.createHash('sha256').update(JSON.stringify({groupId:req.params.groupId,revision:req.body.revision})).digest('hex');const operationId=req.body.operationId;if(operationId!==undefined&&(typeof operationId!=='string'||operationId.length<8||operationId.length>100))throw new ApiError(422,'Ugyldigt operations-id.');const ctx=await context(db,req.user,req.params.groupId);if(operationId){const old=(await db.query('SELECT * FROM approval_operations WHERE school_id=$1 AND operation_id=$2',[req.user.schoolId,operationId])).rows[0];if(old){if(old.fingerprint!==fingerprint)throw new ApiError(409,'Operations-id er allerede brugt til en anden godkendelse.');return old.result;}}const before=await state(db,ctx.group.id);if(req.body.revision!==ctx.dist.revision)throw new ApiError(409,'Fordelingen er ændret. Genindlæs før du godkender.',{revision:ctx.dist.revision});const assignments=(await db.query('SELECT student_id AS "studentId",horse_id AS "horseId" FROM assignments WHERE lesson_id=$1',[ctx.group.lessonId])).rows;const conflicts=validate(ctx,assignments,{complete:true});if(conflicts.length)throw new ApiError(422,'Afklar alle konflikter før godkendelse.',{conflicts,revision:ctx.dist.revision});const revision=ctx.dist.revision+1;await db.query("UPDATE distributions SET status='approved',revision=$2 WHERE group_id=$1",[ctx.group.id,revision]);await snapshot(db,req.user,ctx.group.id,'approved',before);await audit(db,req.user,'Fordeling godkendt',`${ctx.group.name}: ${assignments.length} elever tildelt. Godkendt af ${req.user.name}.`);const result={ok:true,status:'approved',revision};if(operationId)await db.query('INSERT INTO approval_operations VALUES($1,$2,$3,$4,$5)',[req.user.schoolId,operationId,ctx.group.id,fingerprint,JSON.stringify(result)]);return result;});res.json(result);});
function teacher(req){if(req.user.role!=='teacher')throw new ApiError(403,'Kun ridelærere kan redigere heste.');}
function horseInput(body,{partial=false}={}){const clean={};const textFields=['name','kind','temperament','description','status','availabilityReason'];for(const key of textFields)if(body[key]!==undefined){if(typeof body[key]!=='string'||body[key].length>2000)throw new ApiError(422,`Ugyldigt felt: ${key}`);clean[key]=body[key].trim();}if(!partial&&(!clean.name||!clean.kind))throw new ApiError(422,'Hestens navn og type er påkrævet.');if(clean.kind&&!['horse','pony'].includes(clean.kind))throw new ApiError(422,'Vælg hest eller pony.');if(clean.status&&!['available','sick','resting','unavailable'].includes(clean.status))throw new ApiError(422,'Ugyldig tilgængelighed.');for(const [key,min,max] of [['heightCm',70,220],['minRiderLevel',0,5],['maxRiderWeightKg',10,150],['maxDailyLessons',1,3],['maxWeeklyJumps',0,1],['restDay',0,6]])if(body[key]!==undefined){if(!Number.isInteger(body[key])||body[key]<min||body[key]>max)throw new ApiError(422,`Ugyldigt felt: ${key}`);clean[key]=body[key];}if(!partial&&['heightCm','maxRiderWeightKg'].some(k=>clean[k]===undefined))throw new ApiError(422,'Angiv højde og en afklaret maksimal ryttervægt.');if(body.allowedActivities!==undefined){if(!Array.isArray(body.allowedActivities)||!body.allowedActivities.length||body.allowedActivities.some(a=>!['dressage','jumping','trail'].includes(a)))throw new ApiError(422,'Vælg gyldige aktiviteter.');clean.allowedActivities=[...new Set(body.allowedActivities)];}if(body.needs!==undefined){if(!Array.isArray(body.needs)||body.needs.some(n=>typeof n.code!=='string'||typeof n.label!=='string'||!n.code||!n.label||n.code.length>80||n.label.length>200))throw new ApiError(422,'Ugyldige hestebehov.');clean.needs=body.needs;}return clean;}
async function relations(db,id,h){if(h.allowedActivities){await db.query('DELETE FROM horse_activities WHERE horse_id=$1',[id]);for(const a of h.allowedActivities)await db.query('INSERT INTO horse_activities VALUES($1,$2)',[id,a]);}if(h.needs){await db.query('DELETE FROM horse_needs WHERE horse_id=$1',[id]);for(const n of h.needs){await db.query('INSERT INTO needs VALUES($1,$2) ON CONFLICT DO NOTHING',[n.code,n.label]);await db.query('INSERT INTO horse_needs VALUES($1,$2) ON CONFLICT DO NOTHING',[id,n.code]);}}}
app.post('/api/horses',async(req,res)=>{teacher(req);const h=horseInput(req.body);const id=`horse-${crypto.randomUUID()}`;await transaction(async db=>{await lockSchool(db,req.user);await db.query('INSERT INTO horses(id,school_id,name,kind,height_cm,temperament,description,status,availability_reason,max_daily_lessons,rest_day,min_rider_level,max_rider_weight_kg,max_weekly_jumps,source) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)',[id,req.user.schoolId,h.name,h.kind,h.heightCm,h.temperament||'',h.description||'',h.status||'available',h.availabilityReason||null,h.maxDailyLessons??3,h.restDay??0,h.minRiderLevel??0,h.maxRiderWeightKg,h.maxWeeklyJumps??1,'Registreret af ridelæreren']);await relations(db,id,{...h,allowedActivities:h.allowedActivities||['dressage']});await invalidate(db,req.user);await audit(db,req.user,'Hest registreret',`${h.name} er tilføjet med lærerens oplysninger.`);});res.status(201).json({ok:true,id});});
app.patch('/api/horses/:id',async(req,res)=>{teacher(req);const h=horseInput(req.body,{partial:true});await transaction(async db=>{await lockSchool(db,req.user);const found=(await db.query('SELECT * FROM horses WHERE id=$1 AND school_id=$2',[req.params.id,req.user.schoolId])).rows[0];if(!found)throw new ApiError(404,'Hesten findes ikke på rideskolen.');const map={name:'name',kind:'kind',heightCm:'height_cm',temperament:'temperament',description:'description',status:'status',availabilityReason:'availability_reason',maxDailyLessons:'max_daily_lessons',restDay:'rest_day',minRiderLevel:'min_rider_level',maxRiderWeightKg:'max_rider_weight_kg',maxWeeklyJumps:'max_weekly_jumps'};for(const [key,column] of Object.entries(map))if(h[key]!==undefined)await db.query(`UPDATE horses SET ${column}=$2 WHERE id=$1`,[req.params.id,h[key]]);await relations(db,req.params.id,h);await invalidate(db,req.user);await audit(db,req.user,'Hest opdateret',`${h.name||found.name}: oplysninger opdateret.`);});res.json({ok:true});});
const clientDir=fileURLToPath(new URL('../client/dist',import.meta.url));if(existsSync(clientDir)){app.use(express.static(clientDir));app.get('/{*path}',(req,res)=>{if(req.path.startsWith('/api/'))return res.status(404).json({message:'Ukendt API.'});res.sendFile(path.join(clientDir,'index.html'));});}
app.use((err,req,res,next)=>{if(err instanceof ApiError)return res.status(err.status).json({message:err.message,...err.details});if(err.type==='entity.parse.failed')return res.status(400).json({message:'Ugyldig JSON.'});console.error(err);res.status(500).json({message:'Der opstod en fejl. Prøv igen.'});});
await initialize();await seed();await importCaseStudents();await seedHorseImages();const server=app.listen(Number(process.env.PORT||3001),'0.0.0.0',()=>console.log('Stald API ready on port',process.env.PORT||3001));
for(const signal of ['SIGTERM','SIGINT'])process.on(signal,()=>server.close(async()=>{await pool.end();process.exit(0);}));
