import {readFile} from 'node:fs/promises';
import {transaction} from './db.js';
export async function seed(){await transaction(async db=>{await db.query("SELECT pg_advisory_xact_lock(19062026)");if((await db.query('SELECT id FROM schools LIMIT 1')).rows.length)return;
const raw=JSON.parse(await readFile(new URL('../data/horses.json',import.meta.url),'utf8'));const horses=Array.isArray(raw)?raw:raw.horses;
await db.query("INSERT INTO schools VALUES ('demo','Bøgegårdens Ridecenter')");
await db.query("INSERT INTO profiles VALUES ('teacher-anne','demo','Anne · ridelærer','teacher'),('teacher-lars','demo','Lars · ridelærer','teacher')");
const needs=[['calm','Har brug for en rolig hest'],['confidence','Har brug for tryghed'],['experienced','Kræver erfaren rytter'],['gentle','Skånsom belastning'],['no-jumping','Ingen spring'],['small-rider','Lille rytter'],['new-rider','Begynder']];for(const [code,label] of needs)await db.query('INSERT INTO needs VALUES($1,$2)',[code,label]);
for(const [i,h] of horses.entries()){const id=h.id||`horse-${i+1}`;const activities=h.allowedActivities||['dressage','jumping'];await db.query('INSERT INTO horses(id,school_id,name,kind,height_cm,temperament,description,status,availability_reason,max_daily_lessons,rest_day,min_rider_level,max_rider_weight_kg,max_weekly_jumps,source,synthetic_fields) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)',[id,'demo',h.name,h.kind||'Hest',h.heightCm||150,h.temperament||'Se beskrivelse',h.description||'',h.status||'available',h.availabilityReason||null,h.maxDailyLessons??3,h.restDay??0,h.minRiderLevel??0,h.maxRiderWeightKg??(h.needs?.some(n=>n.code==='light-riders')?(h.heightCm<=120?35:45):(h.heightCm<=120?35:h.heightCm<=130?45:h.heightCm<=145?55:h.heightCm<150?65:80)),h.maxWeeklyJumps??1,typeof h.source==='string'?h.source:JSON.stringify(h.source||'base-case-files'),JSON.stringify([...new Set([...(h.syntheticFields||[]),...(h.maxRiderWeightKg==null?['maxRiderWeightKg']:[])])])]);for(const activity of activities)await db.query('INSERT INTO horse_activities VALUES($1,$2)',[id,activity]);for(const n of h.needs||[]){const code=typeof n==='string'?n:n.code;const label=typeof n==='string'?n:n.label;await db.query('INSERT INTO needs VALUES($1,$2) ON CONFLICT DO NOTHING',[code,label]);await db.query('INSERT INTO horse_needs VALUES($1,$2)',[id,code]);}}
const people=[['student-alma','Alma Jensen',1,142,38,'known',['calm']],['student-noah','Noah Larsen',2,155,47,'known',[]],['student-freja','Freja Madsen',2,151,43,'known',['confidence']],['student-oscar','Oscar Nielsen',3,168,58,'known',[]],['student-ella','Ella Sørensen',1,140,36,'new',['calm']],['student-william','William Hansen',2,158,50,'missing',[]],['student-sofia','Sofia Pedersen',3,163,53,'known',[]],['student-lucas','Lucas Andersen',3,170,60,'known',[]]];
for(const [id,name,level,height,weight,state,studentNeeds] of people){await db.query('INSERT INTO profiles VALUES($1,$2,$3,$4)',[id,'demo',name,'student']);await db.query('INSERT INTO students VALUES($1,$2,$3,$4,$5)',[id,level,height,weight,state]);for(const code of studentNeeds)await db.query('INSERT INTO student_needs VALUES($1,$2)',[id,code]);}
const groups=[['group-tuesday','teacher-anne','Tirsdag · begynder',1,'Tirsdag','16:00','dressage','2026-10-06',['student-alma','student-noah','student-freja','student-ella']],['group-friday','teacher-anne','Fredag · let øvet',2,'Fredag','16:00','dressage','2026-10-09',['student-oscar','student-william','student-sofia','student-lucas']],['group-jumping','teacher-lars','Torsdag · spring',3,'Torsdag','17:00','jumping','2026-10-08',['student-oscar','student-sofia']]];
for(const [id,teacher,name,level,day,time,activity,date,students] of groups){await db.query('INSERT INTO groups(id,school_id,teacher_id,name,level,day_label,time,activity) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[id,'demo',teacher,name,level,day,time,activity]);await db.query('INSERT INTO lessons VALUES($1,$2,$3)',[`lesson-${id}`,id,date]);await db.query('INSERT INTO distributions(group_id) VALUES($1)',[id]);for(const student of students){await db.query('INSERT INTO memberships VALUES($1,$2)',[id,student]);const idx=people.findIndex(p=>p[0]===student);const preferred=[['toobi','aslan','belle'],['toobi','zigge','jane'],['aslan','belle','twister'],['pixie','boy','belle'],['toobi','zigge','aslan'],['jane','aslan','belle'],['belle','boy','pixie'],['aslan','pixie','boy']];const chosen=preferred[idx].filter(id=>horses.some(h=>h.id===id));for(const horse of new Set(chosen))await db.query('INSERT INTO wishes VALUES($1,$2,$3,$4)',[student,id,'2026-10',horse]);if(people[idx][5]==='known')for(const month of ['2026-08','2026-09'])await db.query('INSERT INTO month_history VALUES($1,$2,$3,$4,$5)',[student,id,month,chosen[0],false]);}}
await db.query("INSERT INTO schools VALUES ('enghoj','Enghøj Rideskole')");await db.query("INSERT INTO profiles VALUES ('enghoj-teacher','enghoj','Mette · ridelærer','teacher'),('enghoj-student','enghoj','Ida Lund','student')");await db.query("INSERT INTO students VALUES ('enghoj-student',1,145,40,'new')");await db.query("INSERT INTO horses(id,school_id,name,kind,height_cm,temperament,description,status,rest_day,max_rider_weight_kg,source,synthetic_fields) VALUES ('enghoj-horse','enghoj','Sol','pony',145,'Rolig','Syntetisk hest på en anden rideskole.','available',0,55,'Syntetiske demonstrationsdata','[\"maxRiderWeightKg\",\"heightCm\",\"temperament\"]')");await db.query("INSERT INTO horse_activities VALUES('enghoj-horse','dressage')");await db.query("INSERT INTO groups(id,school_id,teacher_id,name,level,day_label,time,activity) VALUES('enghoj-group','enghoj','enghoj-teacher','Onsdag · begynder',1,'Onsdag','16:00','dressage')");await db.query("INSERT INTO memberships VALUES('enghoj-group','enghoj-student')");await db.query("INSERT INTO lessons VALUES('enghoj-lesson','enghoj-group','2026-10-07')");await db.query("INSERT INTO distributions(group_id) VALUES('enghoj-group')");await db.query("INSERT INTO wishes VALUES('enghoj-student','enghoj-group','2026-10','enghoj-horse')");
await db.query("INSERT INTO audit(school_id,actor_id,action,detail) VALUES ('demo','teacher-anne','Demodata oprettet','Elever, ønsker, historik og tekniske grænser er syntetiske demonstrationsdata.')");});}
