// End-to-end API smoke for the synthetic demo. No unit tests.
import assert from 'node:assert/strict';
const base=process.env.BASE_URL||'http://localhost:3005';
let cookie='';
async function request(route,method='GET',body,status=200){const response=await fetch(base+'/api'+route,{method,headers:{...(cookie?{cookie}:{}),...(body?{'content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const result=await response.json();assert.equal(response.status,status,`${method} ${route}: ${JSON.stringify(result)}`);const c=response.headers.get('set-cookie');if(c)cookie=c.split(';')[0];return result;}
await request('/health');const bootstrap=await request('/bootstrap');assert.equal(bootstrap.schools.length,2);
const teacher=bootstrap.profiles.find(p=>p.id==='teacher-anne');const pupil=bootstrap.profiles.find(p=>p.id==='student-alma');assert.ok(teacher&&pupil);
await request('/session','POST',{profileId:teacher.id});let data=await request('/dashboard');assert.equal(data.horses.filter(h=>h.source.includes('fredagsheste')).length,19);assert.ok(data.groups.every(g=>g.teacherName.includes('Anne')));
const group=data.groups.find(g=>g.id==='group-tuesday');let proposal=await request('/distributions/propose','POST',{groupId:group.id});assert.ok(proposal.conflicts.some(c=>c.horseId==='toobi')||group.decisions.some(d=>d.horseId==='toobi'));
const assignments=proposal.assignments.filter(a=>a.studentId!==pupil.id&&a.horseId!=='toobi').map(a=>({studentId:a.studentId,horseId:a.horseId}));assignments.push({studentId:pupil.id,horseId:'toobi'});
const decisions=[{horseId:'toobi',studentId:pupil.id,reason:'Læreren vælger Ellen ved lige ventetid.'}];
for(const conflict of proposal.conflicts){if(!conflict.studentIds?.length||conflict.horseId==='toobi')continue;const chosen={belle:'student-freja',zigge:'student-noah'}[conflict.horseId]||conflict.studentIds[0];decisions.push({horseId:conflict.horseId,studentId:chosen,reason:'Lærerens begrundede valg ved lige ventetid.'});for(let i=assignments.length-1;i>=0;i--)if(assignments[i].studentId===chosen||assignments[i].horseId===conflict.horseId)assignments.splice(i,1);assignments.push({studentId:chosen,horseId:conflict.horseId});}
const saved=await request('/distributions/'+group.id,'PUT',{revision:proposal.revision,assignments,decisions});
const operationId='demo-smoke-approval-'+crypto.randomUUID();const payload={revision:saved.revision,operationId};const approved=await request('/distributions/'+group.id+'/approve','POST',payload);assert.equal(approved.status,'approved');const retry=await request('/distributions/'+group.id+'/approve','POST',payload);assert.deepEqual(retry,approved);
await request('/distributions/'+group.id,'PUT',{revision:saved.revision,assignments},409);
let current=await request('/dashboard');const currentGroup=current.groups.find(g=>g.id===group.id);const duplicate=[...assignments];duplicate[1]={...duplicate[1],horseId:duplicate[0].horseId};await request('/distributions/'+group.id,'PUT',{revision:currentGroup.revision,assignments:duplicate},422);
const sourceHorse=data.horses.find(h=>h.id==='boelle');assert.ok(!sourceHorse.allowedActivities.includes('jumping'));
await request('/session','POST',{profileId:pupil.id});data=await request('/dashboard');assert.deepEqual(data.students.map(s=>s.id),[pupil.id]);assert.ok(data.assignments.some(a=>a.horseId==='toobi'&&a.status==='approved'));
await request('/wishes','PUT',{groupId:group.id,month:'2026-10',horseIds:['toobi','aslan','belle']});await request('/wishes','PUT',{groupId:group.id,horseIds:['toobi','aslan','belle','jane']},422);await request('/wishes','PUT',{groupId:'group-friday',horseIds:['aslan']},403);await request('/wishes','PUT',{groupId:group.id,horseIds:['enghoeje-horse']},422);await request('/distributions/propose','POST',{groupId:group.id},403);
await request('/session','POST',{profileId:bootstrap.profiles.find(p=>p.role==='teacher'&&p.schoolId!==teacher.schoolId).id});const other=await request('/dashboard');assert.notEqual(other.school.id,teacher.schoolId);assert.ok(other.horses.every(h=>h.id!=='toobi'));await request('/horses/toobi','PATCH',{status:'unavailable'},404);
await request('/session','POST',{profileId:teacher.id});data=await request('/dashboard');const g=data.groups.find(g=>g.id===group.id);await request('/horses/toobi','PATCH',{status:'unavailable',availabilityReason:'Demonstration: kontrol af ændret tilgængelighed'});await request('/distributions/'+group.id+'/approve','POST',{revision:g.revision},409);data=await request('/dashboard');await request('/distributions/'+group.id+'/approve','POST',{revision:data.groups.find(g=>g.id===group.id).revision},422);await request('/horses/toobi','PATCH',{status:'available',availabilityReason:''});
const horses=(await request('/dashboard')).horses;if(!horses.some(h=>h.name==='Storm'))await request('/horses','POST',{name:'Storm',kind:'horse',heightCm:154,temperament:'Rolig',description:'Syntetisk registreret demonstrationshest.',maxDailyLessons:2,restDay:0,maxWeeklyJumps:1,minRiderLevel:1,maxRiderWeightKg:65,allowedActivities:['dressage'],needs:[{code:'handling-support',label:'Hjælp til klargøring og håndtering'}]},201);
const beforeFinal=await request('/dashboard');await request('/distributions/'+group.id+'/approve','POST',{revision:beforeFinal.groups.find(g=>g.id===group.id).revision,operationId:crypto.randomUUID()});
const final=await request('/dashboard');assert.ok(final.horses.some(h=>h.name==='Storm'));assert.ok(final.history.some(h=>h.action==='Fordeling godkendt'));
console.log('PASS: PostgreSQL, to skoler, lærer/elev, kildeheste, ønsker, sikkerhedsafvisning, revision, idempotens, godkendelse, historik og hesteregistrering.');
console.log(JSON.stringify({school:final.school.name,sourceHorses:19,registeredHorses:final.horses.length,groups:final.groups.length,students:final.students.length,approvedGroup:group.id}));
